"""Add email to DomainSearch

Revision ID: 03c8893debf7
Revises: d41ef892b0ad
Create Date: 2024-09-28 14:31:50.839639

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03c8893debf7"
down_revision: Union[str, None] = "d41ef892b0ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("domain_searches", sa.Column("email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain_searches", "email")
    # ### end Alembic commands ###
