"""Add embeddings to DomainSearch

Revision ID: 4e4d5ca6f087
Revises:
Create Date: 2024-09-22 09:53:50.740277

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e4d5ca6f087"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "domain_searches", sa.Column("embeddings", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain_searches", "embeddings")
    # ### end Alembic commands ###
