"""Add Association table for DomainSearch<>Listing

Revision ID: 5c6fa8d9445a
Revises: 4e4d5ca6f087
Create Date: 2024-09-22 11:47:55.107058

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c6fa8d9445a"
down_revision: Union[str, None] = "4e4d5ca6f087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("listings_to_domain_searches_rel", sa.Column("score", sa.Float(), nullable=False))
    op.add_column("listings_to_domain_searches_rel", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("listings_to_domain_searches_rel", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listings_to_domain_searches_rel", "updated_at")
    op.drop_column("listings_to_domain_searches_rel", "created_at")
    op.drop_column("listings_to_domain_searches_rel", "score")
    # ### end Alembic commands ###
