"""Add name to DomainSearch

Revision ID: 7f416e43f050
Revises: 03c8893debf7
Create Date: 2024-09-29 10:29:15.353272

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f416e43f050"
down_revision: Union[str, None] = "03c8893debf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("domain_searches", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain_searches", "name")
    # ### end Alembic commands ###
