"""Add column DomainSearch.is_example

Revision ID: d41ef892b0ad
Revises: 5c6fa8d9445a
Create Date: 2024-09-23 16:12:52.250252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d41ef892b0ad"
down_revision: Union[str, None] = "5c6fa8d9445a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("domain_searches", sa.Column("is_example", sa.Boolean(), nullable=True))
    op.execute("UPDATE domain_searches SET is_example = false")
    op.alter_column("domain_searches", "is_example", nullable=False)
    op.add_column("domain_searches", sa.Column("summary", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("domain_searches", "summary")
    op.drop_column("domain_searches", "is_example")
    # ### end Alembic commands ###
