"""ondelete='cascade' for ListingDomainSearch.listing_id

Revision ID: f3f4ea54fc04
Revises: 7f416e43f050
Create Date: 2024-10-15 12:31:34.257816

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3f4ea54fc04"
down_revision: Union[str, None] = "7f416e43f050"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_listings_to_domain_searches_rel_listing_id_listings", "listings_to_domain_searches_rel", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_listings_to_domain_searches_rel_listing_id_listings"),
        "listings_to_domain_searches_rel",
        "listings",
        ["listing_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_listings_to_domain_searches_rel_listing_id_listings"),
        "listings_to_domain_searches_rel",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_listings_to_domain_searches_rel_listing_id_listings",
        "listings_to_domain_searches_rel",
        "listings",
        ["listing_id"],
        ["id"],
    )
    # ### end Alembic commands ###
